package errors

import "errors"

var (
	AccountNotFoundError                       = errors.New("account not found")
	AccountAlreadyExistsForDocumentNumberError = errors.New("an account already exists for this document number")
	CacheConnectionFailedError                 = errors.New("failed to connect to cache")
	CacheConnectionValidationFailedError       = errors.New("cache connection validation error")
	CacheInsertionError                        = errors.New("cache insertion error")
	CacheFailedToDeleteError                   = errors.New("failed to delete from cache error")
	CacheFailedToExpireError                   = errors.New("failed to expire from cache error")
	CacheNotFoundError                         = errors.New("not found in cache")
	ConfigFileNotFountError                    = errors.New("config file not found")
	ConfigFileUnmarshalError                   = errors.New("config unmarshal error")
	DatabaseConnectionFailedError              = errors.New("failed to connect to database")
	DatabaseConnectionValidationFailedError    = errors.New("database connection validation error")
	DatabaseCreateTransactionError             = errors.New("database create transaction error")
	DatabaseFailToCommitError                  = errors.New("database fail to commit error")
	DatabaseInsertionError                     = errors.New("database insertion error")
	DatabasePrepareStatementError              = errors.New("database prepare statement error")
	DatabaseQueryError                         = errors.New("database query error")
	DistributedLockFailToAcquire               = errors.New("distributed lock fail to acquire")
	InvalidParametersError                     = errors.New("invalid parameters")
	OperationTypeNotFoundError                 = errors.New("operation type not found")
	TransactionInvalidAccountIDError           = errors.New("invalid account ID")
	TransactionInvalidAmountNegativeError      = errors.New("invalid amount. must be a positive value")
	TransactionInvalidOperationTypeError       = errors.New("invalid operation type")
	TransactionNotFoundError                   = errors.New("transaction not found")
)
