// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/logger/logger.go
//
// Generated by this command:
//
//	mockgen -package logger -source=./internal/core/logger/logger.go -destination=./internal/core/logger/logger_mock.go -mock_names=Logger=LoggerMock
//

// Package logger is a generated GoMock package.
package logger

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// LoggerMock is a mock of Logger interface.
type LoggerMock struct {
	ctrl     *gomock.Controller
	recorder *LoggerMockMockRecorder
	isgomock struct{}
}

// LoggerMockMockRecorder is the mock recorder for LoggerMock.
type LoggerMockMockRecorder struct {
	mock *LoggerMock
}

// NewLoggerMock creates a new mock instance.
func NewLoggerMock(ctrl *gomock.Controller) *LoggerMock {
	mock := &LoggerMock{ctrl: ctrl}
	mock.recorder = &LoggerMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *LoggerMock) EXPECT() *LoggerMockMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *LoggerMock) Debug(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *LoggerMockMockRecorder) Debug(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*LoggerMock)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *LoggerMock) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *LoggerMockMockRecorder) Error(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*LoggerMock)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *LoggerMock) Info(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *LoggerMockMockRecorder) Info(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*LoggerMock)(nil).Info), varargs...)
}

// Warn mocks base method.
func (m *LoggerMock) Warn(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *LoggerMockMockRecorder) Warn(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*LoggerMock)(nil).Warn), varargs...)
}

// With mocks base method.
func (m *LoggerMock) With(args ...any) Logger {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "With", varargs...)
	ret0, _ := ret[0].(Logger)
	return ret0
}

// With indicates an expected call of With.
func (mr *LoggerMockMockRecorder) With(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*LoggerMock)(nil).With), args...)
}
