// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/lock/distributed_lock_manager.go
//
// Generated by this command:
//
//	mockgen -package lock -source=./internal/core/lock/distributed_lock_manager.go -destination=./internal/core/lock/distributed_lock_manager_mock.go -mock_names=DistributedLockManager=DistributedLockManagerMock
//

// Package lock is a generated GoMock package.
package lock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// DistributedLockManagerMock is a mock of DistributedLockManager interface.
type DistributedLockManagerMock struct {
	ctrl     *gomock.Controller
	recorder *DistributedLockManagerMockMockRecorder
	isgomock struct{}
}

// DistributedLockManagerMockMockRecorder is the mock recorder for DistributedLockManagerMock.
type DistributedLockManagerMockMockRecorder struct {
	mock *DistributedLockManagerMock
}

// NewDistributedLockManagerMock creates a new mock instance.
func NewDistributedLockManagerMock(ctrl *gomock.Controller) *DistributedLockManagerMock {
	mock := &DistributedLockManagerMock{ctrl: ctrl}
	mock.recorder = &DistributedLockManagerMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *DistributedLockManagerMock) EXPECT() *DistributedLockManagerMockMockRecorder {
	return m.recorder
}

// Lock mocks base method.
func (m *DistributedLockManagerMock) Lock(ctx context.Context, key string, ttl time.Duration) (*Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, key, ttl)
	ret0, _ := ret[0].(*Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock.
func (mr *DistributedLockManagerMockMockRecorder) Lock(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*DistributedLockManagerMock)(nil).Lock), ctx, key, ttl)
}

// Unlock mocks base method.
func (m *DistributedLockManagerMock) Unlock(ctx context.Context, acquiredLock *Lock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, acquiredLock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *DistributedLockManagerMockMockRecorder) Unlock(ctx, acquiredLock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*DistributedLockManagerMock)(nil).Unlock), ctx, acquiredLock)
}

// WaitToLock mocks base method.
func (m *DistributedLockManagerMock) WaitToLock(ctx context.Context, key string, ttl, waitingTimeMilliseconds, retryMilliseconds time.Duration) (*Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitToLock", ctx, key, ttl, waitingTimeMilliseconds, retryMilliseconds)
	ret0, _ := ret[0].(*Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitToLock indicates an expected call of WaitToLock.
func (mr *DistributedLockManagerMockMockRecorder) WaitToLock(ctx, key, ttl, waitingTimeMilliseconds, retryMilliseconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitToLock", reflect.TypeOf((*DistributedLockManagerMock)(nil).WaitToLock), ctx, key, ttl, waitingTimeMilliseconds, retryMilliseconds)
}

// WaitToLockUsingDefaultTimeConfiguration mocks base method.
func (m *DistributedLockManagerMock) WaitToLockUsingDefaultTimeConfiguration(ctx context.Context, key string) (*Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitToLockUsingDefaultTimeConfiguration", ctx, key)
	ret0, _ := ret[0].(*Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitToLockUsingDefaultTimeConfiguration indicates an expected call of WaitToLockUsingDefaultTimeConfiguration.
func (mr *DistributedLockManagerMockMockRecorder) WaitToLockUsingDefaultTimeConfiguration(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitToLockUsingDefaultTimeConfiguration", reflect.TypeOf((*DistributedLockManagerMock)(nil).WaitToLockUsingDefaultTimeConfiguration), ctx, key)
}
