// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/factory/factory.go
//
// Generated by this command:
//
//	mockgen -package factory -source=./internal/core/factory/factory.go -destination=./internal/core/factory/factory_mock.go -mock_names=Factory=FactoryMock
//

// Package factory is a generated GoMock package.
package factory

import (
	reflect "reflect"

	handler "github.com/kiosanim/pismo-code-assessment/interfaces/http/handler"
	adapter "github.com/kiosanim/pismo-code-assessment/internal/core/adapter"
	cache "github.com/kiosanim/pismo-code-assessment/internal/core/cache"
	config "github.com/kiosanim/pismo-code-assessment/internal/core/config"
	lock "github.com/kiosanim/pismo-code-assessment/internal/core/lock"
	logger "github.com/kiosanim/pismo-code-assessment/internal/core/logger"
	account "github.com/kiosanim/pismo-code-assessment/internal/domains/account"
	transaction "github.com/kiosanim/pismo-code-assessment/internal/domains/transaction"
	gomock "go.uber.org/mock/gomock"
)

// FactoryMock is a mock of Factory interface.
type FactoryMock struct {
	ctrl     *gomock.Controller
	recorder *FactoryMockMockRecorder
	isgomock struct{}
}

// FactoryMockMockRecorder is the mock recorder for FactoryMock.
type FactoryMockMockRecorder struct {
	mock *FactoryMock
}

// NewFactoryMock creates a new mock instance.
func NewFactoryMock(ctrl *gomock.Controller) *FactoryMock {
	mock := &FactoryMock{ctrl: ctrl}
	mock.recorder = &FactoryMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FactoryMock) EXPECT() *FactoryMockMockRecorder {
	return m.recorder
}

// AccountHandler mocks base method.
func (m *FactoryMock) AccountHandler(accountService account.Service) *handler.AccountHandler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountHandler", accountService)
	ret0, _ := ret[0].(*handler.AccountHandler)
	return ret0
}

// AccountHandler indicates an expected call of AccountHandler.
func (mr *FactoryMockMockRecorder) AccountHandler(accountService any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountHandler", reflect.TypeOf((*FactoryMock)(nil).AccountHandler), accountService)
}

// AccountRepository mocks base method.
func (m *FactoryMock) AccountRepository() account.AccountRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountRepository")
	ret0, _ := ret[0].(account.AccountRepository)
	return ret0
}

// AccountRepository indicates an expected call of AccountRepository.
func (mr *FactoryMockMockRecorder) AccountRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountRepository", reflect.TypeOf((*FactoryMock)(nil).AccountRepository))
}

// CacheConnectionData mocks base method.
func (m *FactoryMock) CacheConnectionData() *adapter.CacheConnectionData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheConnectionData")
	ret0, _ := ret[0].(*adapter.CacheConnectionData)
	return ret0
}

// CacheConnectionData indicates an expected call of CacheConnectionData.
func (mr *FactoryMockMockRecorder) CacheConnectionData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheConnectionData", reflect.TypeOf((*FactoryMock)(nil).CacheConnectionData))
}

// CacheRepository mocks base method.
func (m *FactoryMock) CacheRepository() cache.CacheRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheRepository")
	ret0, _ := ret[0].(cache.CacheRepository)
	return ret0
}

// CacheRepository indicates an expected call of CacheRepository.
func (mr *FactoryMockMockRecorder) CacheRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheRepository", reflect.TypeOf((*FactoryMock)(nil).CacheRepository))
}

// Configuration mocks base method.
func (m *FactoryMock) Configuration() *config.Configuration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Configuration")
	ret0, _ := ret[0].(*config.Configuration)
	return ret0
}

// Configuration indicates an expected call of Configuration.
func (mr *FactoryMockMockRecorder) Configuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configuration", reflect.TypeOf((*FactoryMock)(nil).Configuration))
}

// ConnectionData mocks base method.
func (m *FactoryMock) ConnectionData() *adapter.DatabaseConnectionData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectionData")
	ret0, _ := ret[0].(*adapter.DatabaseConnectionData)
	return ret0
}

// ConnectionData indicates an expected call of ConnectionData.
func (mr *FactoryMockMockRecorder) ConnectionData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectionData", reflect.TypeOf((*FactoryMock)(nil).ConnectionData))
}

// DistributedLockManager mocks base method.
func (m *FactoryMock) DistributedLockManager() lock.DistributedLockManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributedLockManager")
	ret0, _ := ret[0].(lock.DistributedLockManager)
	return ret0
}

// DistributedLockManager indicates an expected call of DistributedLockManager.
func (mr *FactoryMockMockRecorder) DistributedLockManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributedLockManager", reflect.TypeOf((*FactoryMock)(nil).DistributedLockManager))
}

// Log mocks base method.
func (m *FactoryMock) Log() logger.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log")
	ret0, _ := ret[0].(logger.Logger)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *FactoryMockMockRecorder) Log() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*FactoryMock)(nil).Log))
}

// TransactionHandler mocks base method.
func (m *FactoryMock) TransactionHandler(transactionService transaction.Service) *handler.TransactionHandler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionHandler", transactionService)
	ret0, _ := ret[0].(*handler.TransactionHandler)
	return ret0
}

// TransactionHandler indicates an expected call of TransactionHandler.
func (mr *FactoryMockMockRecorder) TransactionHandler(transactionService any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionHandler", reflect.TypeOf((*FactoryMock)(nil).TransactionHandler), transactionService)
}

// TransactionRepository mocks base method.
func (m *FactoryMock) TransactionRepository() transaction.TransactionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionRepository")
	ret0, _ := ret[0].(transaction.TransactionRepository)
	return ret0
}

// TransactionRepository indicates an expected call of TransactionRepository.
func (mr *FactoryMockMockRecorder) TransactionRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionRepository", reflect.TypeOf((*FactoryMock)(nil).TransactionRepository))
}
