// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/cache/cache_repository.go
//
// Generated by this command:
//
//	mockgen -package cache -source=./internal/core/cache/cache_repository.go -destination=./internal/core/cache/cache_repository_mock.go -mock_names=CacheRepository=CacheRepositoryMock
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// CacheRepositoryMock is a mock of CacheRepository interface.
type CacheRepositoryMock struct {
	ctrl     *gomock.Controller
	recorder *CacheRepositoryMockMockRecorder
	isgomock struct{}
}

// CacheRepositoryMockMockRecorder is the mock recorder for CacheRepositoryMock.
type CacheRepositoryMockMockRecorder struct {
	mock *CacheRepositoryMock
}

// NewCacheRepositoryMock creates a new mock instance.
func NewCacheRepositoryMock(ctrl *gomock.Controller) *CacheRepositoryMock {
	mock := &CacheRepositoryMock{ctrl: ctrl}
	mock.recorder = &CacheRepositoryMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CacheRepositoryMock) EXPECT() *CacheRepositoryMockMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *CacheRepositoryMock) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *CacheRepositoryMockMockRecorder) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*CacheRepositoryMock)(nil).Del), ctx, key)
}

// Exists mocks base method.
func (m *CacheRepositoryMock) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *CacheRepositoryMockMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*CacheRepositoryMock)(nil).Exists), ctx, key)
}

// Expire mocks base method.
func (m *CacheRepositoryMock) Expire(ctx context.Context, key string, duration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expire", ctx, key, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Expire indicates an expected call of Expire.
func (mr *CacheRepositoryMockMockRecorder) Expire(ctx, key, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expire", reflect.TypeOf((*CacheRepositoryMock)(nil).Expire), ctx, key, duration)
}

// Get mocks base method.
func (m *CacheRepositoryMock) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *CacheRepositoryMockMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*CacheRepositoryMock)(nil).Get), ctx, key)
}

// HDel mocks base method.
func (m *CacheRepositoryMock) HDel(ctx context.Context, key, fieldName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HDel", ctx, key, fieldName)
	ret0, _ := ret[0].(error)
	return ret0
}

// HDel indicates an expected call of HDel.
func (mr *CacheRepositoryMockMockRecorder) HDel(ctx, key, fieldName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HDel", reflect.TypeOf((*CacheRepositoryMock)(nil).HDel), ctx, key, fieldName)
}

// HExists mocks base method.
func (m *CacheRepositoryMock) HExists(ctx context.Context, key, fieldName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HExists", ctx, key, fieldName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HExists indicates an expected call of HExists.
func (mr *CacheRepositoryMockMockRecorder) HExists(ctx, key, fieldName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HExists", reflect.TypeOf((*CacheRepositoryMock)(nil).HExists), ctx, key, fieldName)
}

// HExpire mocks base method.
func (m *CacheRepositoryMock) HExpire(ctx context.Context, key, fieldName string, duration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HExpire", ctx, key, fieldName, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// HExpire indicates an expected call of HExpire.
func (mr *CacheRepositoryMockMockRecorder) HExpire(ctx, key, fieldName, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HExpire", reflect.TypeOf((*CacheRepositoryMock)(nil).HExpire), ctx, key, fieldName, duration)
}

// HGet mocks base method.
func (m *CacheRepositoryMock) HGet(ctx context.Context, key, fieldName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGet", ctx, key, fieldName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGet indicates an expected call of HGet.
func (mr *CacheRepositoryMockMockRecorder) HGet(ctx, key, fieldName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGet", reflect.TypeOf((*CacheRepositoryMock)(nil).HGet), ctx, key, fieldName)
}

// HGetAll mocks base method.
func (m *CacheRepositoryMock) HGetAll(ctx context.Context, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGetAll", ctx, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGetAll indicates an expected call of HGetAll.
func (mr *CacheRepositoryMockMockRecorder) HGetAll(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGetAll", reflect.TypeOf((*CacheRepositoryMock)(nil).HGetAll), ctx, key)
}

// HSet mocks base method.
func (m *CacheRepositoryMock) HSet(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HSet", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *CacheRepositoryMockMockRecorder) HSet(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*CacheRepositoryMock)(nil).HSet), ctx, key, value, ttl)
}

// Set mocks base method.
func (m *CacheRepositoryMock) Set(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *CacheRepositoryMockMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*CacheRepositoryMock)(nil).Set), ctx, key, value, ttl)
}

// SetNX mocks base method.
func (m *CacheRepositoryMock) SetNX(ctx context.Context, key, value string, duration time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, value, duration)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetNX indicates an expected call of SetNX.
func (mr *CacheRepositoryMockMockRecorder) SetNX(ctx, key, value, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*CacheRepositoryMock)(nil).SetNX), ctx, key, value, duration)
}
